__author__ = 'bglasser'

#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

def fib():
    sum = 0
    p1 = 1
    p2 = 0
    i = 0
    while True:
        result = p1 + p2
        p2 = p1
        p1 = result
        i += 1
        if result >= 4000000: return sum
        if result % 2 == 0:
            sum +=result
            print "%d: %s => %d "%(i, result, sum)
print fib()